qcm/urls.py
from django.urls import path, reverse_lazy, include
from . import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('question/', views.ListQuestions.as_view(), name='list_question'),
    path('question/tag/<str:tag>/', views.ListQuestionsByTag.as_view(), name='list_question_by_tag'),
    path('question/category/<int:category>/', views.ListQuestionsByCategory.as_view(),
         name='list_question_by_category'),
    path('question/import/<int:import_record>/', views.ListQuestionsByImportRecord.as_view(),
         name='list_question_by_import_record'),
    path('question/create/', views.CreateQuestionView.as_view(),
         name='create_question'),
    path('question/update/<int:pk>/', views.UpdateQuestion.as_view(), name='update_question'),
    path('question/delete/<int:pk>/', views.DeleteQuestion.as_view(), name='delete_question'),

    path('search/', views.Search.as_view(), name='search'),
    path('search/results/', views.SearchResults.as_view(), name='search_results'),
]

urlpatterns += [
    path('quiz/', views.ListQuiz.as_view(), name='list_quiz'),
    path('quiz/create/', views.CreateQuiz.as_view(success_url=reverse_lazy('list_quiz')), name='create_quiz'),
    path('quiz/<int:pk>/update/', views.UpdateQuiz.as_view(), name='update_quiz'),
    path('quiz/<int:pk>/delete/', views.DeleteQuiz.as_view(), name='delete_quiz'),
    path('quiz/<int:pk>/duplicate/', views.DuplicateQuiz.as_view(), name='duplicate_quiz'),
    path('quiz/<int:pk>/random/', views.RandomQuiz.as_view(), name='random_quiz'),
    path('quiz/<int:pk>/test/', views.TestQuiz.as_view(), name='test_quiz'),
    path('quiz/<int:pk>/results/', views.ResultsQuiz.as_view(), name='results_quiz'),

    path('quiz/<int:pk>/html/', views.HtmlQuiz.as_view(), name='html_quiz'),
    path('quiz/<int:pk>/latex/', views.LatexQuiz.as_view(), name='latex_quiz'),
    path('quiz/<int:pk>/pdf/', views.PdfQuiz.as_view(), name='pdf_quiz'),
    path('quiz/<int:pk>/pdf/<str:option>/', views.PdfQuiz.as_view(), name='pdf_quiz_with_option'),
    path('quiz/<int:pk>/add/', views.AddQuestionQuiz.as_view(success_url=reverse_lazy('list_quiz')),
         name='add_question_quiz'),
]

urlpatterns += [
    path('quiz/start/<int:code>/', views.StartQuiz.as_view(), name='start_quiz'),

    # path('quiz/results/<int:pk>/', views.SubmissionResults.as_view(), name='results_quiz'),
    path('submission/<int:pk>/', views.TakeQuiz.as_view(), name='submit'),
    path('submission/<int:pk>/lock/', views.LockSubmission.as_view(), name='lock_submission'),
    path('submission/<int:pk>/result/<str:hash>/', views.ResultsSubmission.as_view(), name='results_submission'),
]

urlpatterns += [
    path('vue/', views.Vue.as_view(), name='vue'),
    path('ajax/', views.ajax_test, name='ajax'),
    path('ajax2/', views.ajax_test2, name='ajax2'),
    path('ajax/quiz/', views.ajax_quiz, name='ajax_quiz'),
    path('ajax/questionorder/delete/', views.ajax_questionorder_delete, name='ajax_questionorder_delete'),

]

qcmnsi/urls.py
from django.contrib import admin
from django.urls import path, include
import debug_toolbar


urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),
    #path('admin/', admin.site.urls),
    path('', include('qcm.urls')),
    path('', include('structure.urls')),
    path('', include('importexport.urls')),

]

qcm/models.py
import itertools
import json
import random
import re
import secrets

from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

from pygments import highlight
from pygments.formatters import HtmlFormatter
from pygments.lexers import PythonLexer, JavascriptLexer, SqlLexer
from pygments.lexers.shell import PowerShellLexer
from pygments.lexers.html import HtmlLexer
from taggit.managers import TaggableManager
from .constants import *

from structure.models import Level, Category
from importexport.models import ImportRecord


def convert_html(text):
    text = text.replace('<latex>', '$$$')
    text = text.replace('</latex>', '$$$')

    # mettre en forme le code compris entre les balises <python> avec la librairie pygments
    for block_tags in re.findall('(<python>([\w\W]+?)</python>)', text):
        text = text.replace(block_tags[0], highlight(block_tags[1], PythonLexer(), HtmlFormatter()))
    for block_tags in re.findall('(<js>([\w\W]+?)</js>)', text):
        text = text.replace(block_tags[0], highlight(block_tags[1], JavascriptLexer(), HtmlFormatter()))
    for block_tags in re.findall('(<sql>([\w\W]+?)</sql>)', text):
        text = text.replace(block_tags[0], highlight(block_tags[1], SqlLexer(), HtmlFormatter()))
    for block_tags in re.findall('(<shell>([\w\W]+?)</shell>)', text):
        text = text.replace(block_tags[0], highlight(block_tags[1], PowerShellLexer(), HtmlFormatter()))
    for block_tags in re.findall('(<html>([\w\W]+?)</html>)', text):
        text = text.replace(block_tags[0], highlight(block_tags[1], HtmlLexer(), HtmlFormatter()))
    for block_tags in re.findall('(<esc>([\w\W]+?)</esc>)', text):
        text = text.replace(block_tags[0], block_tags[1].replace('<', '&lt').replace('>', '&gt'))

    return text


def convert_latex(text):
    text = text.replace('&nbsp;', ' ')
    text = text.replace('&lt;', '<')
    text = text.replace('&gt;', '>')
    text = text.replace('%', '$\%$')
    text = text.replace('#', '$\#$')
    text = text.replace('_', '$\_$')
    text = text.replace('\r\n', '\n')  # copier coller depuis pycharm
    # text = text.replace('{', '$\{$')
    # text = text.replace('}', '$\}$')
    text = text.replace('$\{$$\}$', '$\{\}$')  # resultat si dict vide {}
    text = text.replace('<latex>', '$ ')
    text = text.replace('</latex>', ' $')

    # text = text.replace('_', '\_')
    # text = text.replace('#', '\#')
    # mettre en forme le code compris entre les balises <python> avec le module listings
    for block_tags in re.findall('(<python>([\w\W]+?)</python>)', text):
        text = text.replace(block_tags[0], '\\begin{lstlisting}[style=python]' + block_tags[1] + '\\end{lstlisting}')
    # mettre en forme le code compris entre les balises <js> avec le module listings
    for block_tags in re.findall('(<js>([\w\W]+?)</js>)', text):
        text = text.replace(block_tags[0],
                            '\\begin{lstlisting}[style=javascript]' + block_tags[1] + '\\end{lstlisting}')
    # mettre en forme le code en ligne compris entre les balises <tt> avec l'instruction \texttt
    for block_tags in re.findall('(<tt>([\w\W]+?)</tt>)', text):
        text = text.replace(block_tags[0], '\\lstinline[mathescape, style=codestyle]{' + block_tags[1] + '}')

    return text


class Question(models.Model):
    '''
    Question à choix multiples avec une seule réponse correcte
    '''

    # Ordre des questions choisi parmi toutes les permutations de [1, 2, 3, 4]
    ORDERS = [json.dumps(permutation) for permutation in list(itertools.permutations([1, 2, 3, 4]))]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    # todo: enlever level du modele de question car il est accessible par category, pourrait poser problème si on
    # change le niveau d'une catégorie (à revoir avec le chargement dynamique des catégorie en fonction du niveau
    level = models.ForeignKey(Level, on_delete=models.SET_NULL, null=True, blank=False, default=1)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=False, default=11)
    created = models.DateTimeField('Création', auto_now_add=True)
    modified = models.DateTimeField('Dernière modification', auto_now=True)
    text = models.TextField('Enoncé', max_length=2000)
    text_html = models.TextField(max_length=2000, default='')
    text_latex = models.TextField(max_length=2000, default='')
    import_record = models.ForeignKey(ImportRecord, on_delete=models.SET_NULL, null=True)
    tags = TaggableManager('Mots-clés')
    answer_order_json = models.CharField('Ordre des réponses', max_length=32)
    author = models.CharField('Auteur', max_length=128, default='')

    answer1 = models.TextField('Réponse correcte', max_length=2000, )
    answer2 = models.TextField('Réponse incorrecte', max_length=2000)
    answer3 = models.TextField('Réponse incorrecte', max_length=2000)
    answer4 = models.TextField('Réponse incorrecte', max_length=2000)

    answer1_html = models.TextField(max_length=2000, default='')
    answer2_html = models.TextField(max_length=2000, default='')
    answer3_html = models.TextField(max_length=2000, default='')
    answer4_html = models.TextField(max_length=2000, default='')

    answer1_latex = models.TextField(max_length=2000, default='')
    answer2_latex = models.TextField(max_length=2000, default='')
    answer3_latex = models.TextField(max_length=2000, default='')
    answer4_latex = models.TextField(max_length=2000, default='')

    @property
    def answer_order(self):
        return json.loads(self.answer_order_json)

    def first_line(self, limit=None):
        ''' renvoie la premiere ligne de l'énoncé pour la vue compacte d'une question'''
        first_line = self.text_html.split('\n')[0]
        if limit is None:
            return first_line
        elif len(first_line) > limit:
            return first_line[:limit] + '...'
        else:
            return first_line

    def get_answer_html_for_frontend(self, i):
        i = i - 1
        if self.answer_order[i] == 1:
            return self.answer1_html
        elif self.answer_order[i] == 2:
            return self.answer2_html
        elif self.answer_order[i] == 3:
            return self.answer3_html
        elif self.answer_order[i] == 4:
            return self.answer4_html

    def save(self, *args, **kwargs):
        # création de la question

        if self.pk is None:
            # ordre des questions choisi parmi les permutations de [1, 2, 3, 4]
            self.answer_order_json = random.choice(self.ORDERS)

        # générer les versions html des champs
        self.text_html = convert_html(self.text)
        self.answer1_html = convert_html(self.answer1)
        self.answer2_html = convert_html(self.answer2)
        self.answer3_html = convert_html(self.answer3)
        self.answer4_html = convert_html(self.answer4)

        # générer les versions LaTeX des champs
        self.text_latex = convert_latex(self.text)
        self.answer1_latex = convert_latex(self.answer1)
        self.answer2_latex = convert_latex(self.answer2)
        self.answer3_latex = convert_latex(self.answer3)
        self.answer4_latex = convert_latex(self.answer4)

        super(Question, self).save(*args, **kwargs)


class Quiz(models.Model):
    '''
    Ensemble de Questions
    '''
    title = models.CharField('Titre ', max_length=200)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    level = models.ForeignKey(Level, on_delete=models.SET_NULL, null=True, blank=False, default=1)
    created = models.DateTimeField('Création', auto_now_add=True)
    modified = models.DateTimeField('Dernière modification', auto_now=True)
    code = models.PositiveIntegerField('Code ', unique=True)
    questions = models.ManyToManyField(Question, related_name='in_quiz', through='QuestionOrder')
    points_right_answer = models.SmallIntegerField('Points pour une réponse correcte', default=3)
    points_wrong_answer = models.SmallIntegerField('Points pour une réponse fausse', default=-1)

    random_question_order = models.BooleanField('Ordre aléatoire', default=False)
    show_answers = models.BooleanField('Montrer la solution', default=False)

    class Meta:
        ordering = ['-modified']

    @property
    def number_of_questions(self):
        return len(self.questions.all())

    @property
    def points_total(self):
        return self.number_of_questions * self.points_right_answer

    @property
    def stats(self):
        locked_submissions = self.submission_set.exclude(locked=False)
        stats = dict(locked_submissions.aggregate(
            right=models.Avg('count_right') / self.number_of_questions * 100,
            wrong=models.Avg('count_wrong') / self.number_of_questions * 100,
            no_answer=models.Avg('count_no_answer') / self.number_of_questions * 100,
            average=models.Avg('points_scored')),
            locked_submissions=locked_submissions.count())

        return stats

    def authors(self):
        authors = set()
        for question in self.questions.all():
            if question.author != '':
                authors.add(question.author)
        return list(authors)

    def authors_display(self):
        authors = self.authors()
        if len(authors) == 1:
            return authors[0]
        elif len(authors) == 2:
            return authors[0] + ' et ' + authors[1]
        else:
            return ', '.join(authors) + ' et ' + authors[-1]

    def license(self):
        text = 'Ce document est basé sur les travaux de '
        text += self.authors_display()
        text += ''' et est mis à disposition selon les termes de la Licence Creative Commons Attribution - Pas d’Utilisation Commerciale - Partage dans les Mêmes Conditions 4.0'''
        return text

    def generate_latex(self, answer=False):
        # todo: déporter generate latex avecnles fonctions html et latex pour pouvoir reutiliser ca pour l'export de la base

importexport/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views import generic
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.http import HttpResponse

from .models import ImportRecord, ExportRecord
from qcm.models import Question
from qcm.constants import *



@login_required
def import_csv(request):
    '''
    Import de questions à partir d'un fichier CSV
    '''

    record = ImportRecord.objects.create(file_format=CSV,
                                         file_name=request.FILES['csv_file'].name,
                                         user=request.user)
    record.importCSV(request)

    messages.add_message(
        request,
        messages.SUCCESS,
        "L'importation des questions a été réalisée avec succès.",
        extra_tags='Importation réussie')

    return redirect(reverse_lazy('import_question'))


@login_required
def import_xml(request):
    '''
    Import de questions à partir d'un fichier XML
    '''

    record = ImportRecord.objects.create(file_format=XML,
                                         file_name=request.FILES['xml_file'].name,
                                         user=request.user)
    record.importXML(request)

    messages.add_message(
        request,
        messages.SUCCESS,
        "L'importation des questions a été réalisée avec succès.",
        extra_tags='Importation réussie')

    return redirect(reverse_lazy('import_question'))


class ExportQuestion(LoginRequiredMixin, generic.ListView):
    '''
    Page pour exporter la base de questions sous différents formats et voir
    l'historique des opérations d'exportations de questions
    '''
    template_name = 'qcm/question_export.html'
    model = ExportRecord

    def get_queryset(self):
        return ExportRecord.objects.all()


@login_required
def ExportQuestionCSV(request):
    '''
    Exporter toutes les questions au format CSV
    '''
    # todo : ajouter message erreur si l'exportation ne fonctionne pas
    questions = Question.objects.all()
    export = ExportRecord.objects.create(
        format=CSV,
        user=request.user)
    export.exportCSV(questions)

    response = HttpResponse(export.exportCSV(questions), content_type='text/csv')
    filename = f'{export.pk}_sujet'
    response['Content-Disposition'] = f'attachment; filename={filename}.csv'
    return response

    messages.add_message(
        request,
        messages.SUCCESS,
        "L'exportation des questions a été réalisée avec succès.",
        extra_tags="Exportation réussie")

    return redirect(reverse_lazy('export_question'))


@login_required
def ExportQuestionXML(request):
    '''
    Exporter toutes les questions au format XML
    '''

    questions = Question.objects.all()
    export = ExportRecord.objects.create(
        format=XML,
        user=request.user)
    export.exportXML(questions)

    messages.add_message(
        request,
        messages.SUCCESS,
        "L'exportation des questions a été réalisée avec succès.",
        extra_tags="Exportation réussie")

    return redirect(reverse_lazy('export_question'))


class ImportQuestion(LoginRequiredMixin, generic.ListView):
    '''
    Page pour importer des questions à partir d'un fichier et voir
    l'historique des opérations d'import de fichiers
    '''
    template_name = 'qcm/question_import.html'
    model = ImportRecord
    paginate_by = 10

    def get_queryset(self):
        return ImportRecord.objects.select_related('user').all().prefetch_related('question_set')

qcm/templates/qcm/question_export.html
{% extends 'qcm/base.html' %}

{% block pagetitle %}
Exporter les questions
{% endblock %}


{% block content %}


{% include 'qcm/messages.html' %}
<div class="columns">
    <div class="column">
        <p class="title is-4">Exporter la base</p>
        <a href=" {% url 'export_question_csv' %}">
            <button class="button is-info">.CSV</button>
        </a>
        <a href=" {% url 'export_question_xml' %}">
            <button class="button is-info">.XML</button>
        </a>

        <button class="button is-info">.GIFT</button>
        <button class="button is-info">MARKDOWN</button>
        <button class="button is-info">LaTeX</button>

    </div>

    <div class="column">
        <p class="title is-4">Historique</p>
        {% if object_list %}
        <table class="table is-striped">
            <tr>
                <th>

                </th>
                <th>
                    date
                </th>
                <th>
                    questions
                </th>
                <th>
                    lien
                </th>
            </tr>
            {% for export in object_list %}
            <tr>
                <td>
                    <span class="tag is-link is-link">{{export.get_format_display}}</span>
                </td>
                <td>
                    {{export.created}}
                </td>
                <td>
                    {% if export.question_number%}
                        {{ export.question_number }}
                    {% else %}
                    --
                    {% endif %}
                </td>
                <td>
                    {% if export.filepath %}
                    <a href="/qcmnsi/qcmnsi/{{export.filepath}}">{{export.filepath}}</a>
                    {% else %}
                    --
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
        {% else %}
        Aucun export de la base pour le moment
        {% endif %}
    </div>
</div>


{% endblock %}

qcm/templates/qcm/question_form.html
{% extends 'qcm/base.html' %}
{% load add_attr %}

{% block pagetitle %}
{% if object %}
Modifier la question
{% else %}
Ajouter une question
{% endif %}

{% endblock %}


{% block content %}

<form method="post" enctype="multipart/form-data">{% csrf_token %}
    <input type="hidden" name="next" value="{{ request.META.HTTP_REFERER }}">

    <div class="field is-horizontal">
        <div class="field-label is-normal">
            <label class="label">{{form.level.label_tag }}</label>
        </div>
        <div class="field-body">
            <div class="field is-narrow">
                <div class="control">
                    <div class="select is-fullwidth">
                        {{ form.level }}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="field is-horizontal">
        <div class="field-label is-normal">
            <label class="label">{{form.category.label_tag }}</label>
        </div>
        <div class="field-body">
            <div class="field is-narrow">
                <div class="control">
                    <div class="select is-fullwidth">
                        {{ form.category }}
                    </div>
                </div>
            </div>
        </div>
    </div>



    <div class="field is-horizontal">
        <div class="field-label is-normal">
            <label class="label">{{form.text.label_tag }}</label>
        </div>
        <div class="field-body">
            <div class="field">
                <div class="control">
                    {{ form.text }}
                </div>
            </div>
        </div>
    </div>


    <div class="field is-horizontal">
        <div class="field-label is-normal">
            <label class="label" for="id_answer1">{{form.answer1.label_tag }}</label>
        </div>
        <div class="field-body">
            <div class="field">
                <div class="control">
                    {{ form.answer1 }}
                </div>
            </div>
        </div>
    </div>


    <div class="field is-horizontal">
        <div class="field-label is-normal">
            <label class="label" for="id_anwser2">{{form.answer2.label_tag }}</label>

        </div>
        <div class="field-body">
            <div class="field">
                <div class="control">
                    {{ form.answer2 }}
                </div>
            </div>
        </div>
    </div>

    <div class="field is-horizontal">
        <div class="field-label is-normal">
            <label class="label">{{form.answer3.label_tag }}</label>
        </div>
        <div class="field-body">
            <div class="field">
                <div class="control">
                    {{ form.answer3 }}
                </div>
            </div>
        </div>
    </div>

    <div class="field is-horizontal">
        <div class="field-label is-normal">
            <label class="label">{{form.answer4.label_tag }}</label>
        </div>
        <div class="field-body">
            <div class="field">
                <div class="control">
                    {{ form.answer4 }}
                </div>
            </div>
        </div>
    </div>

    <div class="field is-horizontal">
        <div class="field-label is-normal">
            <label class="label">{{form.tags.label_tag}}</label>
        </div>
        <div class="field-body">
            <div class="field">
                <div class="control">
                    {{ form.tags }}
                </div>
            </div>
        </div>
    </div>

    <div class="field is-horizontal">
        <div class="field-label is-normal">
            <label class="label">{{form.author.label_tag }}</label>
        </div>
        <div class="field-body">

            <div class="field">
                <div class="control">
                    <input type="text" class="input is-half" name="author" maxlength="128" required
                           {% if object %} value="{{object.author}}"
                           {% else %} value="{{user.first_name}} {{user.last_name}}" {% endif %}
                           id="id_author">
                </div>
            </div>

        </div>
    </div>

    <div class="field is-horizontal">
        <div class="field-label">
            <!-- Left empty for spacing -->
        </div>
        <div class="field-body">
            <div class="field">
                <div class="control">
                    <button class="button is-primary" type="submit" value="save">
                        Enregistrer
                    </button>
                </div>
            </div>
        </div>
    </div>
</form>


{% endblock %}

qcm/templates/qcm/question_list.html
{% extends 'qcm/base.html' %}

{% block pagetitle %}
{% if category %}
{{category}}
{% elif import_record%}
Importation de {{import_record.file_name }} le {{ import_record.created|date:'d F Y' }} à {{ import_record.created |date:'H:i'}}
{% else %}
Les questions
{% endif %}
{% endblock %}

{% block content %}


{% for question in object_list %}
<div class="columns">
    <div class="column is-2">

    </div>
    <div class="column is-8 ">

        <div class="card">
            <div class="card-content">
                <div class="media">
                    <div class="media-content">
                        <p class="title is-4 is-pulled-left">Question {{ question.pk }}</p>
                        <p class="title is-5 is-pulled-right"> {{question.category.name}}</p>
                    </div>
                </div>
                <div class="content ">
                    {{question.text_html | safe | linebreaks}}

                </div>
                <div class="content">
                    <div class="field">
                        <div class="input is-primary" style="height: auto;">
                            <div class="content" style="width: 100%;">
                                {{question.answer1_html | safe}}
                            </div>
                        </div>
                    </div>
                    <div class="field">
                        <div class="input is-danger" style="height: auto;">
                            <div class="content" style="width: 100%;">
                                {{question.answer2_html | safe}}
                            </div>
                        </div>
                    </div>
                    <div class="field">
                        <div class="input is-danger" style="height: auto;">
                            <div class="content" style="width: 100%;">
                                {{question.answer3_html | safe}}
                            </div>
                        </div>
                    </div>
                    <div class="field">
                        <div class="input is-danger" style="height: auto;">
                            <div class="content" style="width: 100%;">
                                {{question.answer4_html | safe}}
                            </div>
                        </div>
                    </div>
                </div>
                <div>
                    {% if quiz_list %}
                    <div class="field is-horizontal">
                        <div class="field-label is-normal">
                            <label class="label"><label for="id_level">Level :</label></label>
                        </div>
                        <div class="field-body">
                            <div class="field is-narrow">

                                <div class="control">
                                    <div class="select is-fullwidth">
                                        <select name="level" class="select" id="id_level">
                                            {% for quiz in quiz_list %}
                                            <option value="0">{{quiz.title}}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>

                    {% endif %}
                </div>
                <div class="media">
                    <div class="media-content">
                        <div class="tags">
                            {% for tag in question.tags.all %}
                            <a class="tag is-primary" href="{% url 'list_question_by_tag' tag.name %}">
                                {{tag.name}}
                            </a>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="notification is-link ">
            <nav class="level is-mobile">
                <div class="level-item has-text-centered">
                    <div>
                        <i class="fas fa-shopping-basket"></i> <a
                            href="{% url 'delete_question' question.pk %}">Ajouter au panier</a></p>
                    </div>
                </div>
                <div class="level-item has-text-centered">
                    <div>
                        <i class="far fa-edit"></i> <a href="{% url 'update_question' question.pk %}">Modifier</a></p>
                    </div>
                </div>
                <div class="level-item has-text-centered">
                    <div>
                        <i class="far fa-trash-alt"></i> <a
                            href="{% url 'delete_question' question.pk %}">Supprimer</a></p>
                    </div>
                </div>
            </nav>
        </div>
    </div>
</div>

{% empty %}

Aucune question pour le moment.
{% endfor %}


{% endblock %}

qcm/templates/qcm/question_stats.html
{% extends 'qcm/base.html' %}

{% block pagetitle %}
Statistiques
{% endblock %}

{% block content %}


<h2 class="title">Catégorie</h2>
<table class="table">
    {% for category in stats %}
    <tr>
        <td>
            {{category.0}}
        </td>
        <td>
            {{category.1}}
        </td>
    </tr>
    {% endfor %}
</table>


{% endblock %}

qcm/templates/qcm/quiz_duplicate.html
{% extends 'qcm/base.html' %}

{% block pagetitle %}
Dupliquer le quiz
{% endblock %}

{% block content %}

<form method="post">{% csrf_token %}
    <p>Etes-vous sur de vouloir dupliquer le quiz <b>{{ quiz.title }}</b> ?</p>
    <input class="button is-primary" type="submit" value="Confirmer">
</form>

{% endblock %}

qcm/templates/qcm/quiz_html.html
{% load display_answer %}
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>{{object.title}}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.8.1/css/bulma.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
          integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'qcm/css/python_code_highlight.css'%}">
    <style>
        li {list-style-type: none;}
  </style>
    <script>
    MathJax = {
        tex: {
            inlineMath: [['$$$', '$$$'], ['\\(', '\\)']]
            }
    };

    </script>
    <script type="text/javascript" id="MathJax-script" async
            src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js">
    </script>

</head>
<body>

<section class="section">
    <div class="container">
        <h1 class="title is-3">{{object.title}}</h1>
        <hr>
    </div>

    <div class="container">
        <div class="columns">
            <div class="column is-2">
                <img src="https://upload.wikimedia.org/wikipedia/commons/1/12/Cc-by-nc-sa_icon.svg">
            </div>
            <div class="column">
                {{object.license}}
            </div>

        </div>
        <hr>
    </div>

    {% for question in object.questions.all%}
    <div class="container">
        <div class="content">
            <h2 class="title is-4">Question {{ forloop.counter }}</h2>
        </div>
        <div class="content">
            {{question.text_html | safe | linebreaks}}
        </div>
        <div class="content">
            <ul class="fa-ul">
                {% for number in question.answer_order %}
                <li>
                    <span class="fa-li">
                        <i class="far fa-square"></i>
                    </span>{{question | display_answer_html:number | safe | linebreaks}}
                </li>
                {% endfor %}
            </ul>
        </div>
        <hr>
    </div>

    {% endfor %}
</section>

</body>
</html>